["bte"]
verbose        = 1
L              = 2.54E-2   # m
V0             = 100       # V 
freq           = 13.56e6   # Hz
Tg             = 300.0     # K
p0             = 1.0       # Torr

abs_efield_min = 1e-6       # V/m
abs_efield_max = 1e3        # V/m
vspace_ts_type = "BE"


# solver
atol           = 1e-12                      # absolute tolerance
rtol           = 1e-10                      # relative tolerance
gmres_rsrt     = 5                          # number of iterations for GMRES
max_iter       = 300                        # max iterations for the solver
use_gpu        = 0                          # use GPUs 
gpu_device_id  = 0                          # GPU device ID
restore        = 0                          # [1-to restore solver]
rs_idx         = 0                          # restore cycle id    
ic_file        = ""                         # [""- default IC, file path to jump start]
fname          = "bte1d3v"                  # IO dump, file prefix
dir            = "bte1d3v/r3"         # IO dump, folder is created on the fly if not present
plot_data      = 1                          # plot data  
split_scheme   = 0                          # [0- op split scheme, 1- full implicit solve]
io_cycle       = 1e0                        # io output every k-th cycle
cp_cycle       = 1e0                        # checkpoint output every k-th cycle


threads        = 4                          # number of processes used during collision op. assembly 
Np             = 100                        # number of Chebyshev points
Nr             = 63                        # number of B-splines in v-radial   
Nvt            = 16                         # number of ordinates in v-theta
lmax           = 2                          # number of lmodes 
dt             = 2e-4                       # dt/T where T is RF period
collisions     = "lxcat_data/eAr_crs.Biagi.3sp2r" # collision cross-sections
ev_max         = 80                         # eV
ev_extend      = 2                          # [0 =  no extention, 1 = 1.2 ev_max, 2 = log extension (25 * ev_max)]
sp_order       = 3                          # B-spline order
spline_qpts    = 11                         # number of quadrature points to use
Te             = 4                          # eV used to compute electron thermal velocity for v-space normalization
cycles         = 100                        # number of cycles to evolve. 










    
