["glow_1d"]
L      = 2.54E-2   # m
V0     = 100       # V 
freq   = 13.56e6   # Hz
Tg     = 300.0     # K
p0     = 1.0       # Torr
gamma  = 0.01      # only used in fluid model
Teb    = 0.5       # ev

#                  # transport coefficients * n0
De     = 3.86e24   # m^{-1}s^{-1}
mu_e   = 9.66e23   # V^{-1} m^{-1} s^{-1} 

Di     = 2.07e20   # m^{-1} s^{-1}
mu_i   = 4.65e21   # V^{-1} m^{-1} s^{-1}

[solver]
atol           = 1e-12                      # absolute tolerance
rtol           = 1e-10                      # relative tolerance
max_iter       = 300                        # max iterations for the solver
use_gpu        = 0                          # use GPUs 
gpu_device_id  = 0                          # GPU device ID
restore        = 0                          # [1-to restore solver]
rs_idx         = 0                          # restore cycle id    
ic_file        = ""                         # [""- default IC, file path to jump start]
fname          = "1d_glow"                  # IO dump, file prefix
dir            = "1dglow_fluid/r1"          # IO dump, folder is created on the fly if not present
plot_data      = 1                          # plot data  
dirichlet_Te   = 1                          # [1-use dirichlet BC for electron temperature]
io_cycle       = 1e0                        # io output every k-th cycle
cp_cycle       = 1e0                        # checkpoint output every k-th cycle
dt             = 5e-4                       # time step size /RD period
cycles         = 100                        # cycles to run
Np             = 200


[chemistry]
Ns             = 2
NT             = 1
use_tab_data   = 1