integration:
	pdflatex --shell-escape bte_algorithms.tex

algorithms:
	pdflatex --shell-escape bte_algorithms.tex
all:
	pdflatex --shell-escape bte_algorithms.tex
	pdflatex --shell-escape integration.tex
	
	
	
